### PR TITLE
Fix `rx` and `ry` element problems

### PR DESCRIPTION
**Pull request by CubesterYT**
Currently, paper.js ignores lone `rx` or `ry` elements in an SVG, causing it to fail to render properly in the paint editor.

This PR checks the SVG for the existence of either element and the non existence of the other respectively, and adds it.

Currently known SVG makers that have the problem of only exporting with one of the aforementioned elements are Figma and Adobe XD.

Example SVG to test:
Rectangle 1

### CODE REVIEW

**Review by LilyMakesThings — APPROVED** [review]

**Comment by NotCryptid** [comment]
crazy

**Comment by GarboMuffin** [comment]
I think this is the wrong layer to fix it in

**Comment by CubesterYT** [comment]
Which should I do it in instead? I couldn't decide between the file upload handler in the GUI, the svg fix file in the GUI, and this file. Let me know, and I'll open a new PR it the designated location.

**Comment by NotCryptid** [comment]
holy shit they got github in jail what the sigma

**Comment by GarboMuffin** [comment]
since only paper.js can't understand, patch paper.js

**Comment by CubesterYT** [comment]
There's a PR by someone to fix the problem that literally dates back to 2020. Still hasn't been merged.

**Comment by GarboMuffin** [comment]
Great then send it to TurboWarp/paper.js

**Comment by CubesterYT** [comment]
Alright, I'll move it over there

**Comment by CubesterYT** [comment]
https://github.com/TurboWarp/paper.js/pull/1

**Pull request closed without merging**
